
import './globals.css'

import Providers from '@Components/Providers'

export const metadata = {
  title: 'OpeninApp',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body >{children}</body>
      </Providers>
    </html>
  )
}
